### ISSUE TITLE
报错求助

### ISSUE THREAD

**Issue by TRelymc** [SlimefunGuguProject/SlimeTinker#51]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [ ] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/SlimeTinker/issues)，且没有找到相同的问题

### 问题描述

[23:46:31 WARN]: [SlimeTinker] Plugin SlimeTinker vBuild 38 zh-CN(ybw0014) (git fbc3769) generated an exception while executing task 1226
java.lang.IllegalArgumentException: JSON string should not be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.5.jar:git-Paper-672]
        at io.github.sefiraat.slimetinker.guizhanlib.utils.JsonUtil.parse(JsonUtil.java:26) ~[?:?]
        at io.github.sefiraat.slimetinker.guizhanlib.updater.UpdaterTask.getRepoInfo(UpdaterTask.java:78) ~[?:?]
        at io.github.sefiraat.slimetinker.guizhanlib.updater.UpdaterTask.run(UpdaterTask.java:56) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-672]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-672]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-672]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

### 复现步骤

求助

### 预期行为

求助 3Q

### 服务端软件

Spigot

### Minecraft 版本

1.16.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun-v2022.04-release

### 插件版本

SlimeTinker-Build 38 zh-CN(ybw0014) (git fbc3769)

**Comment by ybw0014** [comment]
不要直接在这里发错误日志
该报错无视即可
