### ISSUE TITLE
can't read player locale

### ISSUE THREAD

**Issue by minecraft-fff** [SlimefunGuguProject/SlimeTinker#76]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/SlimeTinker/issues)，且没有找到相同的问题

### 问题描述

[14:05:26 INFO]: UUID of player RotaryApe119114 is 32804ebd-aceb-3a33-ad03-fd508e992545
[14:05:26 INFO]: [SlimeTinker] [ACF] Can't read players locale, you will be unable to automatically detect players language. Only Bukkit 1.7+ is supported for this.
[14:05:26 INFO]: [SlimeTinker] [ACF] java.lang.NoSuchFieldException: locale
[14:05:26 INFO]: [SlimeTinker] [ACF] at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[14:05:26 INFO]: [SlimeTinker] [ACF] at SlimeTinker-Build 45 zh-CN(ybw0014) (git e2c9ca2).jar//io.github.sefiraat.slimetinker.acf.BukkitCommandManager.readPlayerLocale(BukkitCommandManager.java:317)
[14:05:26 INFO]: [SlimeTinker] [ACF] at SlimeTinker-Build 45 zh-CN(ybw0014) (git e2c9ca2).jar//io.github.sefiraat.slimetinker.acf.ACFBukkitListener.onPlayerJoin(ACFBukkitListener.java:57)
[14:05:26 INFO]: [SlimeTinker] [ACF] at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[14:05:26 INFO]: [SlimeTinker] [ACF] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:05:26 INFO]: [SlimeTinker] [ACF] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:53)
[14:05:26 INFO]: [SlimeTinker] [ACF] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[14:05:26 INFO]: [SlimeTinker] [ACF] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.server.players.PlayerList.a(PlayerList.java:445)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:130)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:52)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1350)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1327)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1320)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1298)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[14:05:26 INFO]: [SlimeTinker] [ACF] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311)
[14:05:26 INFO]: [SlimeTinker] [ACF] at java.base/java.lang.Thread.run(Thread.java:833)
[14:05:26 INFO]: RotaryApe119114 joined the game

### 复现步骤

升级到1.20.2的leaves服务器的玩家第一次进服会出现这一坨

### 预期行为

这报错不红不黄的，我也不知道

### 服务端软件

其他 (请在问题描述里写明)

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun v54c1294-Beta

### 插件版本

45

**Comment by ybw0014** [comment]
https://github.com/Sefiraat/SlimeTinker/issues/190
